# Optional: Configure these in Streamlit Cloud dashboard instead
COINGLASS_API_KEY = "your_key_here"
TG_BOT_TOKEN = "your_telegram_bot_token"
TG_CHAT_ID = "your_telegram_chat_id"
```

## **Penjelasan Perubahan:**

1. **Semua kode dalam 1 file** - Menghindari masalah import antar modul
2. **Streamlit Secrets support** - Menggunakan `st.secrets` untuk kredensial yang aman
3. **Fallback ke environment variables** - Jika secrets tidak tersedia
4. **API configuration di UI** - User bisa input API keys langsung di dashboard
5. **Error handling yang lebih baik** - Menangani kasus credentials kosong

## **Cara Deploy di Streamlit Cloud:**

1. Upload file `app.py` dan `requirements.txt` ke GitHub
2. Connect ke Streamlit Cloud
3. Di Streamlit Cloud Dashboard → **Settings → Secrets**, tambahkan (opsional):
```
   COINGLASS_API_KEY = "your_key"
   TG_BOT_TOKEN = "your_bot_token"
   TG_CHAT_ID = "your_chat_id"
